#!/bin/sh
#
# Start logging
#

PIDFILE=/var/lock/server
SERVER=/home/pi/otto-sdk/python/server.py

case "$1" in
  start)
	# exec main
	start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec python -- $SERVER
	;;
  stop)
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec python -- $SERVER
	exit 1
esac

exit $?
